#!/usr/bin/env python3
"""Generate the example equirectangular HDR environment.

Kept in the repo so the shipped asset is reproducible rather than a mystery
binary. Writes Radiance RGBE with new-style per-scanline RLE, which is what
stb_image's HDR loader reads.

The content is a soft studio: a cool-to-warm sky gradient, a dark floor, a sun
disk, and three bright softbox panels. The panels matter -- they are the thing
that makes a *specular* IBL failure obvious. A blurry gradient looks fine even
when the prefilter chain is wrong; rectangular highlights that smear correctly
from sharp to soft as roughness rises do not.

    python tools/make_example_env.py Editor/src/Exported/Env/studio.hdr
"""
import math
import struct
import sys
import os

W, H = 1024, 512


def to_rgbe(r, g, b):
    """Float RGB -> 4-byte RGBE (shared exponent)."""
    m = max(r, g, b)
    if m < 1e-32:
        return (0, 0, 0, 0)
    frac, exp = math.frexp(m)
    scale = frac * 256.0 / m
    return (
        min(255, int(r * scale)),
        min(255, int(g * scale)),
        min(255, int(b * scale)),
        min(255, max(0, exp + 128)),
    )


def rle_channel(vals):
    """New-style Radiance RLE for one channel of one scanline."""
    out = bytearray()
    i = 0
    n = len(vals)
    while i < n:
        # find a run of >= 4 identical bytes
        run = 1
        while i + run < n and vals[i + run] == vals[i] and run < 127:
            run += 1
        if run >= 4:
            out.append(128 + run)
            out.append(vals[i])
            i += run
        else:
            # literal block, up to 128 bytes, stopping before a long run
            start = i
            lit = 0
            while i < n and lit < 128:
                r = 1
                while i + r < n and vals[i + r] == vals[i] and r < 5:
                    r += 1
                if r >= 4:
                    break
                i += 1
                lit += 1
            out.append(lit)
            out.extend(vals[start:start + lit])
    return bytes(out)


def sample(u, v):
    """u in [0,1) longitude, v in [0,1) latitude (0 = top)."""
    phi = (u * 2.0 - 1.0) * math.pi          # -pi..pi
    theta = v * math.pi                      # 0..pi from +Y
    y = math.cos(theta)
    s = math.sin(theta)
    x = s * math.cos(phi)
    z = s * math.sin(phi)

    if y >= 0.0:
        # sky: warm near the horizon, cool overhead
        t = y ** 0.45
        r = 0.45 * (1 - t) + 0.10 * t
        g = 0.55 * (1 - t) + 0.20 * t
        b = 0.72 * (1 - t) + 0.48 * t
    else:
        # floor: dark, slightly warm, with a soft falloff toward nadir
        k = min(1.0, -y * 1.6)
        r, g, b = 0.14 * (1 - k) + 0.05, 0.13 * (1 - k) + 0.045, 0.12 * (1 - k) + 0.04

    # sun
    sun = (math.cos(math.radians(38.0)) * math.cos(math.radians(150.0)),
           math.sin(math.radians(38.0)),
           math.cos(math.radians(38.0)) * math.sin(math.radians(150.0)))
    d = x * sun[0] + y * sun[1] + z * sun[2]
    if d > 0:
        core = 1.0 if d > math.cos(math.radians(1.2)) else 0.0
        glow = d ** 220.0
        r += 42.0 * core + 3.2 * glow
        g += 38.0 * core + 2.8 * glow
        b += 30.0 * core + 2.1 * glow

    # three softbox panels: bright rectangles in longitude/latitude
    for (cu, cv, du, dv, power) in (
        (0.12, 0.30, 0.055, 0.075, 14.0),
        (0.52, 0.26, 0.070, 0.060, 9.0),
        (0.80, 0.36, 0.045, 0.090, 6.0),
    ):
        au = abs(((u - cu + 0.5) % 1.0) - 0.5)
        av = abs(v - cv)
        if au < du and av < dv:
            # soft edges so the panel does not alias into the prefiltered mips
            fu = 1.0 - (au / du) ** 6
            fv = 1.0 - (av / dv) ** 6
            e = power * fu * fv
            r += e
            g += e * 0.985
            b += e * 0.96

    return r, g, b


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "studio.hdr"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    with open(out_path, "wb") as f:
        f.write(b"#?RADIANCE\n")
        f.write(b"# Generated by tools/make_example_env.py\n")
        f.write(b"FORMAT=32-bit_rle_rgbe\n\n")
        f.write(("-Y %d +X %d\n" % (H, W)).encode("ascii"))

        for j in range(H):
            v = (j + 0.5) / H
            chans = ([], [], [], [])
            for i in range(W):
                u = (i + 0.5) / W
                rgbe = to_rgbe(*sample(u, v))
                for c in range(4):
                    chans[c].append(rgbe[c])
            f.write(struct.pack("BBBB", 2, 2, (W >> 8) & 0xFF, W & 0xFF))
            for c in range(4):
                f.write(rle_channel(chans[c]))

    print("wrote %s (%d x %d, %.0f KB)" %
          (out_path, W, H, os.path.getsize(out_path) / 1024.0))


if __name__ == "__main__":
    main()
